# docker-compose.yml
version: "3.6"
services:
  ojs:
    privileged: true
    build:
      context: .
    ports: 
      - 8181:80
    environment: 
      - PKP_DATABASE_DRIVER=mysqli
      - PKP_DATABASE_HOST=mysql
      - PKP_DATABASE_USERNAME=ojs
      - PKP_DATABASE_PASSWORD=ojs
      - PKP_DATABASE_NAME=ojs
      - MOUNT_POINT=/var/s3
      - PKP_FILES_FILES_DIR=${MOUNT_POINT}/ojs/files
      - PKP_FILES_PUBLIC_FILES_DIR=${MOUNT_POINT}/ojs/public
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=ojs
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs
      - MYSQL_ROOT_PASSWORD=root

volumes: 
  db_data:
