# docker-compose.yml
version: "3.6"
services:
  ojs:
    build:
      context: https://github.com/arturluizbr/docker-pkp-ojs.git
      args:
        - tag_name=ojs-3_1_2-4
    volumes:
      - ./ojs_files:/var/files
      - ./ojs_public_files:/var/www/html/public
    ports: 
      - 8181:80
    env_file: .env
    environment: 
      - PKP_GENERAL_INSTALLED="On"
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=ojs
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs
      - MYSQL_ROOT_PASSWORD=root

volumes: 
  db_data:
  ojs_files:
  ojs_public_files:

